# Generated by Django 5.1.3 on 2024-12-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.TextField(max_length=500, verbose_name='Текст сообщения'),
        ),
    ]
