# Generated by Django 5.1.3 on 2024-11-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
