# Generated by Django 5.0.1 on 2024-02-21 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
