# Generated by Django 5.0.1 on 2024-02-21 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_users_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
