# Generated by Django 5.1.3 on 2024-11-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_users_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
