# Generated by Django 5.0.1 on 2024-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_users_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
