# Generated by Django 5.1.3 on 2024-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_users_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='theme',
            field=models.CharField(default='Light', max_length=15),
        ),
    ]
