# Generated by Django 5.1.5 on 2025-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
