# Generated by Django 5.1.6 on 2025-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_is_online_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
