# Generated by Django 5.1.6 on 2025-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
