# Generated by Django 5.0.1 on 2024-02-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_message_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
