# Generated by Django 5.0.1 on 2024-02-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_receiver_message_reciever'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
