# Generated by Django 5.0.1 on 2024-06-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
