# Generated by Django 5.0.1 on 2024-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_message_time_created_alter_message_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.TimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
    ]
