# Generated by Django 5.1.6 on 2025-07-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
